# Generated by Django 4.1.2 on 2022-11-11 13:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AreaCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('disponivel', models.BooleanField(blank=True, default=True)),
                ('apta', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Plantacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('qntDiasColheita', models.IntegerField(null=True)),
                ('qntPlantada', models.IntegerField(null=True)),
                ('dtPlantio', models.DateTimeField(default=datetime.datetime.today)),
                ('colhida', models.BooleanField(default=False)),
                ('areacultivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.areacultivo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
        migrations.CreateModel(
            name='Tarefas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('data', models.DateTimeField(default=datetime.datetime.today)),
                ('tipoTarefa', models.TextField(choices=[('PLANTACAO', 'Em uma plantação'), ('AREA', 'Em uma área'), ('LIVRE', 'Livre')], default=0, max_length=20, null=True)),
                ('concluida', models.BooleanField(default=False)),
                ('areacultivo', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.areacultivo')),
                ('plantacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.plantacao')),
            ],
        ),
        migrations.CreateModel(
            name='Irrigacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dtUltIrrigacao', models.DateField(default=datetime.datetime.today, null=True)),
                ('dtProxIrrigacao', models.DateField(default=datetime.datetime.today, null=True)),
                ('horario', models.TimeField()),
                ('duracao', models.TimeField()),
                ('concluida', models.BooleanField(default=False)),
                ('programacao', models.TextField(choices=[('NAO_REPETE', 'Não se repete'), ('TODOS_DIAS', 'Todos os dias')], default=0, max_length=20, null=True)),
                ('plantacao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plantacao')),
            ],
        ),
    ]
