# Generated by Django 4.1.1 on 2022-11-09 14:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areacultivo',
            name='disponivel',
            field=models.BooleanField(blank=True, default=True),
        ),
        migrations.AlterField(
            model_name='plantacao',
            name='colhida',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='plantacao',
            name='dtPlantio',
            field=models.DateTimeField(default=datetime.datetime.today),
        ),
    ]
