# Generated by Django 4.1.1 on 2022-11-14 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='avatar',
            field=models.ImageField(null=True, upload_to='media'),
        ),
    ]
