# Generated by Django 4.1.2 on 2022-11-11 18:39

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tarefa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=100)),
                ('data', models.DateField(default=datetime.datetime.today)),
                ('tipoTarefa', models.TextField(choices=[('PLANTACAO', 'Em uma plantação'), ('AREA', 'Em uma área'), ('LIVRE', 'Livre')], default=0, max_length=20, null=True)),
                ('concluida', models.BooleanField(default=False)),
                ('areacultivo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.areacultivo')),
                ('plantacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.plantacao')),
            ],
        ),
        migrations.AlterField(
            model_name='irrigacao',
            name='dtProxIrrigacao',
            field=models.DateField(blank=True, default=datetime.datetime.today, null=True),
        ),
        migrations.AlterField(
            model_name='irrigacao',
            name='dtUltIrrigacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Tarefas',
        ),
    ]
