# Generated by Django 4.1.1 on 2022-11-02 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='irrigacao',
            name='duracao',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='irrigacao',
            name='horario',
            field=models.DateTimeField(),
        ),
    ]
