# Generated by Django 4.1.1 on 2022-09-26 00:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AreaCultivo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=45)),
            ],
        ),
        migrations.CreateModel(
            name='Irrigação',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('horario', models.DateTimeField(auto_now_add=True)),
                ('duração', models.TimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Plantação',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descrição', models.CharField(max_length=100)),
                ('dPlantio', models.DateTimeField(auto_now_add=True)),
                ('areacultivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.areacultivo')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.categoria')),
            ],
        ),
        migrations.DeleteModel(
            name='Planta',
        ),
        migrations.AddField(
            model_name='irrigação',
            name='plantacao',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.plantação'),
        ),
    ]
