# Generated by Django 4.1.1 on 2022-11-03 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_irrigacao_duracao_alter_irrigacao_horario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='areacultivo',
            name='apto',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='areacultivo',
            name='disponivel',
            field=models.BooleanField(default=True),
        ),
    ]
