# Generated by Django 4.1.2 on 2022-11-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_areacultivo_disponivel_alter_plantacao_colhida_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantacao',
            name='qntDiasColheita',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='plantacao',
            name='qntPlantada',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='areacultivo',
            name='nome',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
