# Generated by Django 4.1.1 on 2022-11-15 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_users_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='plantacao',
            name='qntColhida',
            field=models.IntegerField(null=True),
        ),
    ]
