# Generated by Django 4.1.1 on 2022-11-15 21:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_areacultivo_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='areacultivo',
            name='user',
        ),
    ]
